[alembic]
script_location = alembic

sqlalchemy.url = sqlite:///./test.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = simple

[logger_root]
level = WARN
handlers = console

[handler_console]
class = StreamHandler
level = NOTSET
formatter = simple
args = (sys.stderr,)

[formatter_simple]
format = %(levelname)-5.5s [%(name)s] %(message)s